### ISSUE TITLE
Exception Thrown

### ISSUE THREAD

**Issue by valavakilian** [died/YOLO3-With-OpenCvSharp4#1]
Hi. thanks for the response and sorry for asking so many questions.
I am now trying this repository and I get the following error : 
System.TypeInitializationException: 'The type initializer for 'OpenCvSharpYolo3.Program' threw an exception.'
Inner Exception:
DirectoryNotFoundException: Could not find a part of the path 'C:\Users\V\YOLO3-With-OpenCvSharp4\YOLO3-With-OpenCvSharp4\OpenCvSharpYolo3\bin\Content\coco.names'.

I checked and coco does exist in the file. I'm not sure if I'm missing something very obvious mistake.
thank you for your help and support.

**Comment by died** [comment]
@valavakilian please make sure the file and path is right, and [here](https://github.com/died/YOLO3-With-OpenCvSharp4/blob/26b913ea188f384da3ac0eec7c494d3bcef20019/OpenCvSharpYolo3/Program.cs#L35) have a setting for the path, check it too.

or you can modify code, just put all things into debug folder then test again, avoid path issue.

**Comment by valavakilian** [comment]
Thanks a lot for your help. There was a problem with downloading the files and the content was never saved in the bin folder. I though it was a problem with direct and relative path but I was wrong.
I will close this and thanks a lot for your help
