### ISSUE TITLE
OpenCvSharp4 how to load yolo weight and config to predict with classifier trained

### ISSUE THREAD

**Issue by badpaybad** [died/YOLO3-With-OpenCvSharp4#11]
Hi 
I try this guider , I got weight file. 
`https://github.com/AlexeyAB/darknet/wiki/Train-Classifier-on-ImageNet-(ILSVRC2012)`
the cmd of darknet: to predict
`./darknet classifier predict cfg/imagenet1k.data cfg/csdarknet53-omega.cfg backup/csdarknet53-omega_last.weights dog.jpg`

How to implement code c# similar to 'classifier predict' it with opencvsharp 
Tks in advance

**Comment by died** [comment]
I think you can download the weight, put to right place
change the weight name in here
https://github.com/died/YOLO3-With-OpenCvSharp4/blob/master/OpenCvSharpYolo3/Program.cs

If lucky the network was same format, it maybe can work, or you need modify the code to get result from network.
