### ISSUE TITLE
Using OpenCV for Unity

### ISSUE THREAD

**Issue by valavakilian** [died/YOLO3-With-OpenCvSharp4#2]
Sorry to ask such a question but do you think you can use this program with opencv for unity. I'm asking this because I have to run this application on a unity package.
Thanks for your help

**Comment by died** [comment]
@valavakilian I never used OpenCV for Unity, but I checked the document
https://enoxsoftware.github.io/OpenCVForUnity/3.0.0/doc/html/annotated.html
https://shimat.github.io/opencvsharp_docs/html/d75eb659-6335-53f6-af7a-81814a21ab7f.htm
Seems they are a little different, so if you want to use this code, you have to mapping the different method name.

**Comment by valavakilian** [comment]
Thanks a lot . I will look into this more.
