### ISSUE TITLE
hi  “ net.Forward(outs, outNames); “  i run your code in video stream but very slow.

### ISSUE THREAD

**Issue by vc815** [died/YOLO3-With-OpenCvSharp4#3]
hi 
hi  “ net.Forward(outs, outNames); “  i run your code in video stream but very slow.
"net.Forward(outs, outNames); "  2 seconds per frame. Is there any way to speed it up?
thank you  very much

**Comment by died** [comment]
@vc815 The forward is slow because running on CPU, if using CUDA(GPU) then it can be fast, but seems OpenCvSharp didn't support it, maybe you can try [OpenCv](https://opencv.org/) and using GPU to do it.
Or you can build your own OpenCvSharp with GPU enable.

**Comment by zhangyufei1995** [comment]
@vc815  what is your vs and opencvsharp verison?

**Comment by vc815** [comment]
@died  Thank you for your reply。It seems  that  what your say
@zhangyufei1995  vs2017 .  Thank you for your reply

**Comment by zhangyufei1995** [comment]
看你起来你是中国人，能加您qq吗 ------------------ 原始邮件 ------------------
发件人: "vc815"<notifications@github.com>
发送时间: 2019年6月17日(星期一) 晚上8:43
收件人: "died/YOLO3-With-OpenCvSharp4"<YOLO3-With-OpenCvSharp4@noreply.github.com>;
抄送: "zhangyufei1995"<2424661975@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [died/YOLO3-With-OpenCvSharp4] hi  “ net.Forward(outs, outNames); “  i run your code in video stream but very slow. (#3)



@died  Thank you for your reply。It seems  that  what your say
 @zhangyufei1995  vs2017 .  Thank you for your reply
 
&mdash;
