### ISSUE TITLE
hello why the code erro?

### ISSUE THREAD

**Issue by zhangyufei1995** [died/YOLO3-With-OpenCvSharp4#4]
![捕获](https://user-images.githubusercontent.com/45422726/59581175-a6749400-9106-11e9-91bc-2ff2416b6dfb.JPG)

**Comment by zhangyufei1995** [comment]
and what is your visual studio version ?

**Comment by zhangyufei1995** [comment]
and what is your oepncvsharp version?

**Comment by died** [comment]
@zhangyufei1995  please make you have install/reinstall [OpenCvSharp4](https://www.nuget.org/packages/OpenCvSharp4/) from nuget. VS version didn't matter.

**Comment by zhangyufei1995** [comment]
@died Must I install it from Nuget?  thanks

**Comment by zhangyufei1995** [comment]
@died I downloaded the 4.1 DLL manually and then quoted it, but it made an error.

**Comment by died** [comment]
@zhangyufei1995 try get it from nuget ?

**Comment by zhangyufei1995** [comment]
i changed some codes .it can works,but some erros as follow



“System.TypeInitializationException”类型的未经处理的异常在 mscorlib.dll 中发生 

其他信息: “OpenCvSharpYolo3.Program”的类型初始值设定项引发异常。

**Comment by Zuzuske** [comment]
Best way to get rid of issues is to use NuGet package manager and get the necessary packages. 

For OpenCVSharp4 to work you need to get the main package along with the runtime package.

Its as easy as that.
