### ISSUE TITLE
How do we restrict the detection to faces only

### ISSUE THREAD

**Issue by johnjake** [died/YOLO3-With-OpenCvSharp4#5]
Hey zhangyufei1995!

Thank you for sharing this, I really appreciate it and its save me huge amount of time, but how do we restrict on faces only? As I am working with face recognition and emgucv was a bit slow, so I'm looking for face detection using yolo and for facial recognition using opencvsharp is this possible? also real time face detection ? 

Once again thank you very much for sharing 

Best Regards 

John

**Comment by Zuzuske** [comment]
Hey John, 

I know that this might be late.
You have 2 possible solutions. 
First one is to get a pre-trained weights that might have face class in it, then implement logic using classIds and not render a rectangle which class is not face.

Second solution would be to train a model yourself with just a face class. Not very difficult but very time consuming. 

BR
Vytautas.
